[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"
  
# The Netlify Next.js plugin will handle API routes and other routing automatically.
[[plugins]]
  package = "@netlify/plugin-nextjs"
