[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Next.js는 자체적으로 라우팅을 처리하므로 리다이렉트가 필요하지 않음
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
#   force = false
